<a href="https://colab.research.google.com/github/Sadanan643021272-0/python_dataviz2023/blob/main/Final2023_DataViz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

MessageError: ignored

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import os
import numpy as np

In [ ]:
os.chdir('/content/gdrive/MyDrive/DataViz23Data/final')
!pwd #เช็ค path ที่กำลังทำงานอยู่

/content/gdrive/MyDrive/DataViz23Data/final

In [ ]:
df1 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_operator_logs_20171207-20171219.csv')
df1

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
...,...,...,...,...,...,...
4703,8,14,171219106014514,2017-12-19T22:00:22,264,OperatorSignOff
4704,1,21,171219106021873,2017-12-19T22:02:53,124,OperatorSignOn
4705,8,15,171219106015506,2017-12-19T22:05:05,265,OperatorSignOff
4706,1,21,171219106021890,2017-12-19T22:09:47,124,OperatorSignOff
4707,1,22,171219106022935,2017-12-19T22:12:44,146,OperatorSignOff

In [ ]:
df2 = pd.read_csv('/content/gdrive/MyDrive/DataViz23Data/final/POS_transactions_20171207-20171219.csv')
df2

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...
66858,1,1712191060847,2017-12-19T11:48:35,2017-12-19T11:49:28,606,53,19,6,True,False,36.27
66859,1,1712191060848,2017-12-19T11:49:47,2017-12-19T11:50:24,606,37,15,10,True,False,43.16
66860,1,1712191060849,2017-12-19T11:50:39,2017-12-19T11:51:22,606,43,14,11,False,True,39.58
66861,1,1712191060851,2017-12-19T11:51:36,2017-12-19T11:52:28,606,52,9,9,False,True,113.96
66862,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58

In [ ]:
print(df1.isnull().any())
print(df2.isnull().any())

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool
WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [ ]:
P2017 = df2.merge(df1, how ='left', left_on='OperatorID',right_on='OperatorID')
print(P2017.shape)
P2017

(7328682, 16)

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
1,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022506,2017-12-07T15:04:20,OperatorLock
2,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022507,2017-12-07T15:04:57,OperatorUnLock
3,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022509,2017-12-07T15:05:47,OperatorLock
4,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022510,2017-12-07T15:06:58,OperatorUnLock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7328677,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060831,2017-12-19T11:32:55,OperatorLock
7328678,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060832,2017-12-19T11:33:16,OperatorUnLock
7328679,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060845,2017-12-19T11:41:57,OperatorLock
7328680,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060846,2017-12-19T11:48:24,OperatorUnLock
7328681,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,1712191060855,2017-12-19T11:55:11,OperatorSignOff

In [ ]:
P2017nodrop = P2017.drop_duplicates(subset='TranID_x')
P2017nodrop

,WorkstationGroupID_x,TranID_x,BeginDateTime_x,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,WorkstationGroupID_y,WorkstationID,TranID_y,BeginDateTime_y,Items
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
258,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
516,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
774,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
1032,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1,22,171207106022462,2017-12-07T14:23:11,OperatorSignOn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7328342,1,1712191060847,2017-12-19T11:48:35,2017-12-19T11:49:28,606,53,19,6,True,False,36.27,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328410,1,1712191060848,2017-12-19T11:49:47,2017-12-19T11:50:24,606,37,15,10,True,False,43.16,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328478,1,1712191060849,2017-12-19T11:50:39,2017-12-19T11:51:22,606,43,14,11,False,True,39.58,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328546,1,1712191060851,2017-12-19T11:51:36,2017-12-19T11:52:28,606,52,9,9,False,True,113.96,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn
7328614,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58,1,8,171207106082,2017-12-07T10:08:12,OperatorSignOn

In [ ]:
P2017nodrop.to_csv('P2017.csv', index=False)